name: gg_process
description: GgProcess is a wrapper around Process.run and Process.start. It allows us to mock the execution of console programs.
version: 1.0.0
repository: https://github.com/inlavigo/gg_process.git

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.4.2
  collection: ^1.18.0
  colorize: ^3.0.0
  path: ^1.8.0

dev_dependencies:
  gg:
    git: https://github.com/inlavigo/gg.git
  lints: ^3.0.0
  pana: ^0.22.1
  test: ^1.24.0
